language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: pOZ0CZWRcFSFJXqG3pOcqT1c9y5LMfIowSH/SYM/fZDJ9deNFzTFMXTdWvSqYsf52V3akre6cWGwrYoix0TvtSg1fgOJI/03jUw7Vqwq24+B9W2TBFhoi5jfqLHXsJWkT/Q5W6URjj8LVy2H+znqYyMADz8iD2n+uCJqZJiGoL/V5gNPLFVDJZ37mthLLSTUUPSr1DmsRHnkPwgvQx5WdTtmzRRcsbPYORBBk1ZvhwvnmC12NyCGD91KcZvyhnY+nH7s4LF+KXPerkZdonkBRPzVjDxFNFJ72dtmg1Hf6YeCrfDBJxOF5CRttYIuA5P2fXy2h3ONsjCflH/ItThfsKUuCj5VR/sraoVDTNt1n0GkiknPajKunX6DjCM1Q8PZRXFY7c3Py6s/k4pKwfgbTX1+xBUh15idkwyao0bmE/Jw/jl45bqAMWiFGlGq2c+MODJKoUIPwsOjZhg72YJNUSOwFh9LCznmh7l1gd9dLtQJs1S8lh0Sh48NC4vU+cfJG6La2Go8MkzDPOHJ9h1OaUIl8Dl+QZP+fuBJlzVSKulCZPQnllMe3u9YmFzX6ViqwBixjZCppkxR1rfPkTbo2SQOmfibPE8HxyxLiVLyVbUwsAWFN56lWszYvwh91w19Dc7U8ORe4+/Bjmj8d2vWVk35s5WZqL+PZtgWzui12r0=
  app: mysterious-hollows-29572
